TEST_CASE("predicate")
{
    REQUIRE(PredicateEq<int>(1)(1));
    REQUIRE(PredicateNe<int>(1)(0));
    REQUIRE(PredicateLe<int>(1)(1));
    REQUIRE(PredicateLe<int>(1)(0));
    REQUIRE(PredicateLt<int>(1)(0));
    REQUIRE(PredicateGe<int>(1)(1));
    REQUIRE(PredicateGe<int>(1)(2));
    REQUIRE(PredicateGt<int>(1)(2));
}
